apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adminapp-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapp-db
spec:
  selector:
    matchLabels:
      app: adminapp-db
  replicas: 1
  template:
    metadata:
      labels:
        app: adminapp-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: DB_HOST
              value: adminapp-db
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_DATABASE
              value: adminapp-db
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: adminapp-db-pvc
