apiVersion: v1
kind: Pod
metadata:
  name: dns-test-pod
spec:
  containers:
    - name: dns-test-container
      image: busybox
      command: ['sh', '-c', 'while true; do nslookup adminapp-db; sleep 10; done']
