apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-test
  template:
    metadata:
      labels:
        app: dns-test
    spec:
      containers:
        - name: dns-test-container
          image: mn21/dns-test-image:latest
